/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://t33y3w7apralbnzpelgyg3gf5a.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-f5a33xgabff5ham54zlgwnqwlu",
    "aws_cognito_identity_pool_id": "us-east-1:c01bcdf6-b2c5-4beb-a424-34c904d42b3c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_nDLob0bid",
    "aws_user_pools_web_client_id": "6ilj5q1llkf3q6cekheej9bfu4",
    "oauth": {
        "domain": "mydomainvtex.auth.us-east-1.amazoncognito.com",
        "scope": [
            "aws.cognito.signin.user.admin",
            "email",
            "openid",
            "phone"
        ],
        "redirectSignIn": "https://www.localhost",
        "redirectSignOut": "https://www.youtube.com",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
