/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = import.meta.env

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": config.VITE_AWS_APPSYNC_GRAPHQLENDPOINT,
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": config.VITE_AWS_APPSYNC_AUTHENTICATIONTYPE,
    "aws_appsync_apiKey": config.VITE_AWS_APPSYNC_APIKEY,
    "aws_cognito_identity_pool_id": config.VITE_AWS_COGNITO_IDENTITY_POOL_ID,
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": config.VITE_AWS_USER_POOLS_ID,
    "aws_user_pools_web_client_id": config.VITE_AWS_USER_POOLS_WEB_CLIENT_ID,
    "oauth": {
        "domain": config.VITE_DOMAIN,
        "scope": [
            "aws.cognito.signin.user.admin",
            "email",
            "openid",
            "phone"
        ],
        "redirectSignIn": "https://www.localhost",
        "redirectSignOut": "https://www.youtube.com",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
